# FOSSA Configuration for Lacuna
# https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md
#
# Lacuna is an Apache 2.0 licensed Python library.
# Python packages are dynamically linked/imported at runtime, not statically linked.

version: 3

project:
  id: github.com/witlox/lacuna
  name: lacuna
  url: https://github.com/witlox/lacuna

# Path filtering - exclude test and development directories
paths:
  exclude:
    - tests
    - htmlcov
    - docs
    - .venv
    - lacuna.egg-info

# Target configuration
targets:
  only:
    - type: pip
      path: .

# Notes on license compliance:
#
# False positives from bundled components (these packages are permissively licensed):
# - numpy: BSD-3-Clause (GPL flags from bundled BLAS/LAPACK headers)
# - scipy: BSD-3-Clause (GPL flags from bundled Fortran/BLAS components)
# - torch: BSD-3-Clause (GPL flags from bundled GCC runtime)
# - ruff: MIT (GPL flags from tree-sitter grammars - dev dependency only)
# - setuptools: MIT (GPL flags from vendored code)
# - psycopg2-binary: LGPL-3.0 (dynamic linking is compliant)
#
# These issues should be marked as resolved in the FOSSA dashboard:
# https://app.fossa.com/projects/git%2Bgithub.com%2Fwitlox%2Flacuna
#
# LGPL dependencies (like psycopg2-binary):
#   - LGPL allows dynamic linking without source disclosure
#   - Python imports are dynamic linking, not static
#   - This is compliant with Apache 2.0 distribution
#
# For more details on Python package licensing and dynamic linking:
# https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic
